import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import StoreProvider from '@/app/StoreProvider'
import NavigationBar from '@/components/NavigationBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'DnF | 내 캐릭터 찾기, 랭킹보기',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="">
          <StoreProvider>
            <NavigationBar />
            <main className="pt-28">{children}</main>
          </StoreProvider>
        </div>
      </body>
    </html>
  )
}
