import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import StoreProvider from '@/app/StoreProvider'
import NavigationBar from '@/components/NavigationBar'
import { persistStore } from 'redux-persist'
import { PersistGate } from 'redux-persist/integration/react'
import { makeStore } from '@/lib/redux/store'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className={inter.className}>
          <header>
            <NavigationBar />
          </header>
          <main className="pt-40">{children}</main>
        </body>
      </StoreProvider>
    </html>
  )
}
