import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import StoreProvider from '@/app/StoreProvider'
import NavigationBar from '@/components/NavigationBar'
import Footer from '@/components/Footer'
import { Suspense } from 'react'
import DarkModeProvider from '@/app/DarkModeProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'DnF | 내 캐릭터 찾기, 랭킹보기',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}  `}>
        <Suspense fallback={<div>...loading</div>}>
          <DarkModeProvider>
            <StoreProvider>
              <NavigationBar />
              <Suspense fallback={<div>...loading</div>}>
                <main className="pt-28">{children}</main>
              </Suspense>
            </StoreProvider>
            <Footer />
          </DarkModeProvider>
        </Suspense>
      </body>
    </html>
  )
}
